Blog app: View
manzitresor/blog_app pull request #6
Opened 2023-09-28 16:55 UTC by manzitresor

### Implemented Feature

- [ ] Add Users View
- [ ] Add Post view

2023-09-28 18:39 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @manzitresor 

Good job so far 👏! I really appreciate the effort you put in!  **_However, there are few this that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)


## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Good job with the design
- ✅ Descriptive PR and README file
- ✅ Correct Linters

## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 18:39 UTC, KanzaTahreem commented on app/views/users/_userHeader.html.erb
- [ ] Well done for using partials 👏👏 However, kindly make sure to follow the [given wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_root_users.png?token=GHSAT0AAAAAAB5V373VVI5PWZ5PEIRSLGRUZIVZSMQ) for styling. This is how the current design looks like 👇 Don't forget to fix it for all the other pages

![image](https://github.com/manzitresor/blog_app/assets/106119105/af20039f-c703-4c66-9fb2-f229e2076246)

2023-09-28 18:39 UTC, KanzaTahreem commented on app/views/users/show.html.erb
- [ ] Great effort so far 👏👏Similarly here, kindly make sure to follow the [given wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_user_page.png?token=GHSAT0AAAAAAB5V373VA3ZXWGVRCKEM4UHKZIV2LOA) for styling. This is how the current design looks like 👇 

![image](https://github.com/manzitresor/blog_app/assets/106119105/c2f34341-a32d-4330-92b5-efa8fcacfd37)

2023-09-28 18:39 UTC, KanzaTahreem commented on app/views/posts/index.html.erb
- [ ] Here as well, please make sure to follow the given wireframe for styling

![image](https://github.com/manzitresor/blog_app/assets/106119105/5baeebe9-0b7c-43af-a87f-d72ad563c0cc)

2023-09-28 18:39 UTC, KanzaTahreem commented on app/views/posts/show.html.erb
> +  <% end %>
- [ ] Amazing effort so far👏✨ Please make sure that post show page displays post with all comments listed as shown on the [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_single_post.png) ⛏ This is what we have right now 👇

![image](https://github.com/manzitresor/blog_app/assets/106119105/5a08c46f-768d-4c88-ae1b-75bebf4d4d2c)

2023-09-28 22:20 UTC, jerryowusu requested changes
Hi @manzitresor 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![noooo](https://github.com/manzitresor/blog_app/assets/65233860/6ab66bed-b7ae-4619-9726-33872e6b8fc8)

 ## Highlights
Database working fine :+1: 
Creates users and posts :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 22:20 UTC, jerryowusu commented on app/views/posts/show.html.erb
> +  <% end %>
Nice job so far. However, as requested by the previous reviewer, kindly make sure that this show page displays all the comments of a given post and not just the 5 recent comments. 

### Your design 

![Screenshot from 2023-09-28 22-13-39](https://github.com/manzitresor/blog_app/assets/65233860/9698aac4-a97a-4193-8231-c805123ac8c9)



### Given wireframe

![Screenshot from 2023-09-28 22-17-52](https://github.com/manzitresor/blog_app/assets/65233860/18f20daa-608c-49fc-bbbc-a92fbaf60755)

2023-09-29 06:19 UTC, binhussen approved these changes
Hi @manzitresor , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Added Views ✔️
- Well Structured Code ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-29 06:23 UTC, merged